language: node_js
node_js:
  - "node"
  - "lts"
  - "8"

branches:
  only:
  - master

install: yarn install --ignore-engines

script:
  - npm test

after_success:
  - npm run coveralls

sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
