language: node_js
node_js:
  - "lts/*"
  - "10"

branches:
  only:
  - master

install: yarn install

script:
  - npm run build
  - npm test

after_success:
  - npm run coveralls

cache:
  yarn: true

