language: node_js
node_js:
  - "9"
  - "8"
  - "6"

branches:
  only:
  - master

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH=$HOME/.yarn/bin:$PATH

script:
  - npm test

after_success:
  - npm run coveralls
