language: node_js
node_js:
  - "lts/*"
  - "10"

branches:
  only:
  - master

install: yarn install

script:
  - yarn test:unit
  - yarn build

after_success:
  - yarn coveralls

cache:
  yarn: true

