language: node_js
node_js:
  - "node"
  - "lts/*"
  - "8"

branches:
  only:
  - master

install: yarn install --ignore-engines

script:
  - npm test

after_success:
  - npm run coveralls

sudo: required
before_install:
  - npm install -g node-gyp
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.14.0
  - export PATH=$HOME/.yarn/bin:$PATH

# https://stackoverflow.com/a/40802733/5642633
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
cache:
  yarn: true
